apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doctor-booking

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

# Set the name prefix for all resources
namePrefix: doctor-booking-

# Add a common label to all resources
commonLabels:
  app: doctor-booking
  environment: base
