apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # These values should be base64 encoded
  # Example: echo -n 'your-secret' | base64
  JWT_SECRET: ""  # Will be injected from Terraform
  DB_HOST: ""     # Will be injected from Terraform
  DB_PORT: ""     # Will be injected from Terraform
  DB_NAME: ""     # Will be injected from Terraform
  DB_USER: ""     # Will be injected from Terraform
  DB_PASSWORD: "" # Will be injected from Terraform
