apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Import the base configuration
resources:
  - ../../base
  - ingress.yaml

# Override the namespace
namespace: doctor-booking-production

# Common labels for all resources
commonLabels:
  env: production

# Configure the backend deployment
patches:
  - target:
      kind: Deployment
      name: doctor-booking-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENV
          value: production
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 211125312702.dkr.ecr.us-east-1.amazonaws.com/doctor-booking-api:production
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

  # Configure the frontend deployment
  - target:
      kind: Deployment
      name: doctor-booking-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 211125312702.dkr.ecr.us-east-1.amazonaws.com/doctor-booking-frontend:production
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

  # Override base Secret values for production (avoid duplicate secret)
  - target:
      kind: Secret
      name: doctor-booking-secrets
    patch: |-
      - op: add
        path: /stringData
        value:
          DB_PASSWORD: xsa798xas7x9a8s9x78s7x8
          JWT_SECRET: nxlklsjxalsxsa9xa09sx8a08sx09a8sx

generatorOptions:
  disableNameSuffixHash: true
